services:
  postgres:
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - /Users/gianlucazicca/private/dev/docker/postgres/pg-protimerDB-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=protimer_db
